<?php

$reviews = array(
    'Phoenix' => '<div class="embedsocial-hashtag" data-ref="e27f3e9e8147ede461f3ea8376c516059edb9d77"></div> <script> (function(d, s, id) { var js; if (d.getElementById(id)) {return;} js = d.createElement(s); js.id = id; js.src = "https://embedsocial.com/cdn/ht.js"; d.getElementsByTagName("head")[0].appendChild(js); }(document, "script", "EmbedSocialHashtagScript")); </script>',
    'Los Angeles'  => '<div class="embedsocial-hashtag" data-ref="0ad6096610a7de8c10a800321a22538542329bf2"></div> <script> (function(d, s, id) { var js; if (d.getElementById(id)) {return;} js = d.createElement(s); js.id = id; js.src = "https://embedsocial.com/cdn/ht.js"; d.getElementsByTagName("head")[0].appendChild(js); }(document, "script", "EmbedSocialHashtagScript")); </script>',
    'Sacramento'  => '<div class="embedsocial-hashtag" data-ref="6aed9ceac31dbb0a282a43729335982678326c68"></div> <script> (function(d, s, id) { var js; if (d.getElementById(id)) {return;} js = d.createElement(s); js.id = id; js.src = "https://embedsocial.com/cdn/ht.js"; d.getElementsByTagName("head")[0].appendChild(js); }(document, "script", "EmbedSocialHashtagScript")); </script>',
    'Riverside' => '<div class="embedsocial-hashtag" data-ref="dc81482f9c4be085244a68bb41cad837c3f1a4e7"></div> <script> (function(d, s, id) { var js; if (d.getElementById(id)) {return;} js = d.createElement(s); js.id = id; js.src = "https://embedsocial.com/cdn/ht.js"; d.getElementsByTagName("head")[0].appendChild(js); }(document, "script", "EmbedSocialHashtagScript")); </script>',
    'Fort Lauderdale' => '<div class="embedsocial-hashtag" data-ref="f3d8a10e53a5219ea2ffe69dcfac5cd24db4db17"></div> <script> (function(d, s, id) { var js; if (d.getElementById(id)) {return;} js = d.createElement(s); js.id = id; js.src = "https://embedsocial.com/cdn/ht.js"; d.getElementsByTagName("head")[0].appendChild(js); }(document, "script", "EmbedSocialHashtagScript")); </script>',
    'Jacksonville' => '<div class="embedsocial-hashtag" data-ref="55fe7bfeb698b4ecb2ed6fb0cb713c4b432a2596"></div> <script> (function(d, s, id) { var js; if (d.getElementById(id)) {return;} js = d.createElement(s); js.id = id; js.src = "https://embedsocial.com/cdn/ht.js"; d.getElementsByTagName("head")[0].appendChild(js); }(document, "script", "EmbedSocialHashtagScript")); </script>',
    'Orange County' => '<div class="embedsocial-hashtag" data-ref="00af23ac3356d0831ad617448eb4fbae477d07c9"></div> <script> (function(d, s, id) { var js; if (d.getElementById(id)) {return;} js = d.createElement(s); js.id = id; js.src = "https://embedsocial.com/cdn/ht.js"; d.getElementsByTagName("head")[0].appendChild(js); }(document, "script", "EmbedSocialHashtagScript")); </script>'
    ); 